package com.agora.assemblee.common.enums;
public enum OwnerType { LEGISLATIVE_TEXT, TEXT_VERSION, COMMITTEE, PLENARY_SESSION, DEPUTY, WORKFLOW_INSTANCE, FINANCE_RECORD, CITIZEN_CONSULTATION, INTERNAL_MESSAGE }
